govuk-one-login/ipv-cri-common-express

- src/routes/oauth2/middleware.js
- src/routes/oauth2/middleware.test.js
`state` and `redirect_uri` are returned on a successful init session call. We should save them in our session so that we can use them for any error handling that needs to happen, as well as a successful return journey after the CRI has finished its main purpose.
> Store redirect_uri and state from initial oauth call

- src/lib/oauth.js
- src/lib/oauth.test.js
- src/routes/oauth2/middleware.test.js
`redirect_url` (L) and `redirect_uri` (I) were being used inconsistently.
This PR aligns them to the oauth standard of `redirect_uri` (I)
> fix: Use consistent redirect_uri instead of redirect_url

- src/routes/oauth2/middleware.js
- src/routes/oauth2/middleware.test.js
Rename `AUTHORIZE` to `SESSION` to match the naming on the backend systems.
> refactor: Rename API.AUTHORIZATON to API.SESSION to match backend

- src/lib/error-handling.js
- src/lib/error-handling.test.js
- src/lib/index.js
- src/lib/oauth.js
Add generic error handling as an [Express error handler](https://expressjs.com/en/guide/error-handling.html).
This means that if there is an uncaught Axior error, or it is passed on, the error middleware will be able to use the API response for `error code`, `error message` & `redirect_uri` if available.
> Add oauth redirect error handling

- src/components/base-form.njk
- src/components/base-page.njk
Use footer / phaseBanner content from `i18n` rather than hardcode into template
> refactor: Use footer content from i18n files

- src/components/unrecoverable-error.njk
Added a templated unrecoverable error page.
The text and components have been created using templates we can override the variables to give translations or alternative text.
For example in your project you could have a view like so 
```
{% extends "unrecoverable-error.njk" %}
{% set pageTitle = "not so unrecoverable" %}
```
As part of the unrecoverable error handling, we should have error pages that portray more information.
By adding it to common-express we can reuse it across multiple CRIs
By using templates we can override text accordingly.
- [KBV-390](https://govukverify.atlassian.net/browse/KBV-390)
> KBV 390 create-unrecoverable-error-page

- src/lib/error-handling.js
- src/lib/error-handling.test.js
Use the original error when displaying an error page.
The code is currently relying on `URL` throwing, and then that error is passed on, which means all unhandled errors become URL parsing errors. Which is not helpful.
> fix: Use original error in next()

- .prettierignore
- src/assets/javascript/.eslintrc.js
- src/assets/javascript/application.js
- src/assets/javascript/cookies.js
- src/components/banner.njk
- src/components/base-form.njk
- src/components/base-page.njk
- src/lib/locals.js
- src/lib/settings.js
- src/lib/strings.js
Add support for GTM, based upon the implementation in authentication, with support for customisation per credential issuer
To use the frontend JavaScript here will require changes to the build process of the Express applications.
- [KBV-276](https://govukverify.atlassian.net/browse/KBV-276)
> feat: Add GTM based upon authentication-frontend

- src/components/base-form.njk
- src/components/base-page.njk
Added role = "complementary" to phase banner so that all elements in a basic page are contained in landmarks
So that pages meet WCAG accessibility requirements
- [LIME-86](https://govukverify.atlassian.net/browse/LIME-86)
> LIME-86 - Updating Phase banner to be contained in landmarks

- package.json
- scripts/checkTranslations.js
- scripts/checkTranslations.test.js
- scripts/testFiles/fail/cy/default.yml
- scripts/testFiles/fail/en/default.yml
- scripts/testFiles/success/cy/default.yml
- scripts/testFiles/success/en/default.yml
Adds a check to set the field to be a simple string when we know its a `null` and not a `undefined`. 
When a yaml script has a empty field it registers it as missing and thus fails the check. This check adds a `_` when we see null. If the field is undefined, then the translation library has failed to find it. 
The bug occurred because we're only checking for truthiness of the field and not whether the field exists or not. For example if a key exists but the field is null, then it fails.
> Bugfix: Script fails when the field is empty on both files

- src/lib/error-handling.js
- src/lib/error-handling.test.js
Oauth error handling
To take in error code and description properly, and return access denied oauth error for integration with CRI callback to ipv core (e.g when a user escapes there journey in driving licence cri)
> LIME-147 - Updating Error handling for access denied oauth error

- src/routes/oauth2/middleware.js
- src/routes/oauth2/middleware.test.js
There is currently an inconsistency with the common API endpoints - some of them use `session-id` and some of them use `session_id`.
In order to non-breaking refactoring on the API - all the API requests will temporarily provide both parameters. Once the refactoring is complete, the unused parameter can be removed.
- [OJ-962](https://govukverify.atlassian.net/browse/OJ-962)
> refactor: Send session_id & session-id for BE refactoring

- package.json
- scripts/checkTranslations.js
- scripts/checkTranslations.test.js
- scripts/testFiles/plurals/cy/default.yml
- scripts/testFiles/plurals/en/default.yml
- yarn.lock
- i18next provides support for plurals, but plural forms differ between languages
https://www.unicode.org/cldr/cldr-aux/charts/29/supplemental/language_plural_rules.html
lodash.differenceWith is used to apply a set difference over the language keys
> feat: Add plurals support to checkTranslations script

- src/lib/i18next/index.js
- src/lib/i18next/index.test.js
i18next needs to be set on the main router, not on the app as received from the bootstrap.
> fix: Use router not app for i18next

- package.json
- src/lib/axios.js
- src/lib/axios.test.js
- src/lib/user-ip-address.js
- src/lib/user-ip-address.test.js
- yarn.lock
Get Client IP address and send it to backend via Session API header. 
used "x-forwarded-for"  header value from /session api.
Get Client IP Address and assigned the IP address on  header "x-forwarded-for" for session API .
To reuse Client IP address of client to send to TXMA.
- [OJ-924](https://govukverify.atlassian.net/browse/OJ-923)
> OJ-923 : Send client IP address from all CRI frontends

- src/components/base-form.njk
- src/components/base-page.njk
Added aria role "button" to back button for base pages and base forms
To make webPages compliant with the latest accessibility standards
> LIME-149 - Adding landmark to back button for accessibility

- src/components/banner.njk
- src/components/base-form.njk
- src/components/base-page.njk
Correct a typo in banner.njk (cookieBannerAccept/cookieBannerReject)
PR amended to use the same fix by @wilsond-gds https://github.com/alphagov/di-ipv-cri-common-express/pull/166 and also apply https://github.com/alphagov/di-ipv-cri-common-express/pull/167
Missing text in Driving License/Passport-v1 fronts was traced to a typo that had been replicated though existing CRI front ends.
- [LIME-633](https://govukverify.atlassian.net/browse/LIME-633)
- [LIME-665](https://govukverify.atlassian.net/browse/LIME-665)
[LIME-633]: https://govukverify.atlassian.net/browse/LIME-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-665]: https://govukverify.atlassian.net/browse/LIME-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> LIME-633 Fix typo in banner.njk (cookieBannerAccept/cookieBannerReject)

- README.md
- src/components/base-form.njk
- src/components/base-page.njk
The `govukHeader` components found in `base-form.njk` and `base-page.njk` have been updated to include the flag `useTudorCrown: true`
This change is required in order to activate the new crown for Identity UIs on February 19th
- [DCP-2997](https://govukverify.atlassian.net/browse/DCP-2997)
[DCP-2997]: https://govukverify.atlassian.net/browse/DCP-2997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DCP-2997] Add useTudorCrown flag to nunjucks template headers

- README.md
- src/components/base-form.njk
- src/components/base-page.njk
The `govukHeader` components found in `base-form.njk` and `base-page.njk` have been updated to include the flag `useTudorCrown: true`
This is a backport of #330 
This change is required in order to activate the new crown for Identity UIs on February 19th
- [DCP-2997](https://govukverify.atlassian.net/browse/DCP-2997)
[DCP-2997]: https://govukverify.atlassian.net/browse/DCP-2997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCP-2997: Add useTudorCrown flag to nunjucks template headers

- src/lib/helmet.js
The `helmet.js` CSP object has been extended to include GA4 domains
Content Security Policy errors were appearing in the console for GA4 tracker events in the Address and KBV CRIs
- [DFC-485](https://govukverify.atlassian.net/browse/DFC-485)
[DFC-485]: https://govukverify.atlassian.net/browse/DFC-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DFC-485] - Update CSP to include GA4 domains

- src/components/base-form.njk
- src/components/base-page.njk
- src/components/unrecoverable-error.njk
[OJ-2570] Accessibility Fix - Focus on Error Summary
added initialisation for the govuk frontend.
to fix the issue of the focus not being pulled to the error summary
- [OJ-2570]https://govukverify.atlassian.net/browse/OJ-2571
[OJ-2570]: https://govukverify.atlassian.net/browse/OJ-2570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-2570]: https://govukverify.atlassian.net/browse/OJ-2570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> added initialisation for the govuk frontend.

- CODE_OF_CONDUCT.md
- SECURITY.md
Add security guide and code of conduct copied from https://github.com/govuk-one-login/.github/tree/main
> Add security guide and code of conduct

- package-lock.json
- package.json
- src/lib/error-handling.js
- src/lib/error-handling.test.js
Have been advised by Lime team to release this as a breaking change as they are uncertain of the impact it may have.
`error-handling.js` added check to see if the `redirect_uri` is present within `redirectAsErrorToCallback` method and `redirect_uri` is undefined then display the error page.
CRI's were getting the following error message: `Cannot read properties of undefined (reading 'redirect_uri')` and this was causing users to not go to an appropriate error screen. 
Some teams were adding a fix to their own [frontends](https://github.com/govuk-one-login/ipv-cri-bav-front/blob/5f3f22a211b1a3cd38d36d40b75083d0a5053c91/src/app.js#L160) but given it's happening everywhere, it's better to fix it here. 
Full error message:
```
{"@timestamp":"2024-08-19T14:56:19.443Z","level":"ERROR","message": …
```
> OJ-2724: Show the error page if the `redirect_uri` is not set/`authParams` is undefined

- README.md
- package-lock.json
- package.json
- src/components/base-form.njk
- src/components/base-page.njk
- src/lib/locals.js
- src/lib/settings.js
- test/lib/locals.test.js
- The feature flags to enable/disable GA4 and UA have been renamed positively, switching from `ga4Disabled` to `ga4Enabled`
- Each of the trackers now has its own flag
- The original naming of the global flags was confusing as it reversed the boolean value. Setting it to `true` meant that the package was turned off
- Now that the package is live, a greater level of control is needed for regressions and bugs to not have a large impact that risks a rollback being required. With these flags, if any trackers start sending PII or experiencing another issue, we can turn that tracker off but continue to collect analytics data
- [DFC-648](https://govukverify.atlassian.net/browse/DFC-648)
[DFC-648]: https://govukverify.atlassian.net/browse/DFC-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
> [DFC-648] - Update existing GA4 feature flags and add tracker flags

- src/lib/locals.js
- test/lib/locals.test.js
As part of the latest Language Toggle improvements, the active URL is now constructed using new URL() with string concatenation. While error handling is currently handled at the middleware level, adding error handling during the URL parsing process provides a more reliable solution.
A try-catch block has been added to CE, and additional error handling will be implemented within the package itself. This ensures that users can continue to navigate as usual, even if the current URL cannot be retrieved, avoiding issues with setting the URL with the language parameters which is required for the toggle to work.
- [DFC-581](https://govukverify.atlassian.net/browse/DFC-581)
[DFC-581]: https://govukverify.atlassian.net/browse/DFC-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> DFC-581 - Extend the URL construction in the  middleware to handle an error being thrown.

- src/components/base-form.njk
- src/components/base-page.njk
Removed class which created an inconsistency in the margins below the language toggle
Fixing inconsistency
(https://govukverify.atlassian.net/browse/DFC-742)
Verified that this is consistent across CRI and non-CRI repositories as tested on driving licence (CRI) and Mobile ID Check (non-CRI) margins match up as screenshots demonstrate.
> [DFC-742] style(742): removed margin-bottom-1 from both base-form and base-page

- .secrets.baseline
- src/bootstrap/middleware/headers.js
- src/lib/README.md
- src/lib/helmet.js
- src/lib/strings.js
Asynchronously generates nonce for CSP following [this guide ](https://helmetjs.github.io/faq/csp-nonce-example/)
The existing implementation was synchronously generating a nonce blocking the event loop multiple times on every page. This has a negative impact on performance of the overall application
Before
After
And no CSP related errors in the console
- [OJ-2927](https://govukverify.atlassian.net/browse/OJ-2927)
[OJ-2927]: https://govukverify.atlassian.net/browse/OJ-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2927: Asynchronously generates nonce for CSP

- src/components/base-form.njk
- src/components/base-page.njk
- Removed `role: complementary` from `govukPhaseBanner` on base form and base page nunjuck files
One of the issues found during accessibility testing found [here] (https://docs.google.com/spreadsheets/d/1wRBtzKKZK8FFXBje7UMK0y7yzuMkigOt6rK0BD3_Ou0/edit?gid=0#gid=0)
- [OJ-2977](https://govukverify.atlassian.net/browse/OJ-2977)
[OJ-2977]: https://govukverify.atlassian.net/browse/OJ-2977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2977: Fix - removed role from govukPhaseBanner

- src/lib/error-handling.js
- src/routes/oauth2/middleware.js
Increase logging around redirects
To debug server_error being passed back to redirect URI
- [PYIC-7942](https://govukverify.atlassian.net/browse/PYIC-7942)
[PYIC-7942]: https://govukverify.atlassian.net/browse/PYIC-7942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PYIC-7942: Increase logging around redirects

- src/components/base-form.njk
- src/components/base-page.njk
base-form.njk and base-page.njk amended to reflect required tab title suffix change from _"... GOV.UK"_ to _"... - GOV.UK One Login"_
This discrepancy was flagged in an accessibility audit which found this title suffix was inconsistent with the rest of the service. 
Evidence in ticket.
- [LIME-1508](https://govukverify.atlassian.net/browse/LIME-1508)
[LIME-1508]: https://govukverify.atlassian.net/browse/LIME-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1508 pageTitle suffix amended to GOV.UK One Login

- src/bootstrap/middleware/error-handler.js
- src/lib/error-handling.js
- src/lib/error-handling.test.js
- test/bootstrap/middleware/spec.error-handler.js
When a user encounters an error on any Lime owned frontend, and their session lacks a valid redirecturl, session token and state, the system returns a more appropriate 403 Forbidden error instead of the generic 500 error.
Validation added to error-handling.js to assign MISSING_AUTHPARAMS error code
error code validation added to error-handler.js to assign 403 error status
The system returns a 403 error and redirects to the default error page which is more informative than the generic 500 error.
- [LIME-1543](https://govukverify.atlassian.net/browse/LIME-1543)
[LIME-1543]: https://govukverify.atlassian.net/browse/LIME-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1543  Add error handling for missing authparams

- package-lock.json
- package.json
Creating new release which includes migration of overload-protection into Common-express. 
Overload protection has more coverage if moved closer to the creation of the express app, which happens in bootstrap of common-express.
> Release v10.6.0

- README.md
- src/components/base-form.njk
- src/components/base-page.njk
- src/lib/locals.js
- src/lib/settings.js
- test/lib/locals.test.js
This PR adds support for the [GDS One Login Device Intelligence node package](https://www.npmjs.com/package/@govuk-one-login/frontend-device-intelligence).
- Base nunjuck templates updated to include new script behind a feature flag
- Added functions to set required environment variables
To enable CRI teams to use the Device Intelligence package
- [KIWI-2249](https://govukverify.atlassian.net/browse/KIWI-2249)
[KIWI-2249]: https://govukverify.atlassian.net/browse/KIWI-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2249 - Add support for Device Intelligence 

- src/lib/locals.js
- test/lib/locals.test.js
Added small fix for device intelligence feature flag - this now mirrors the implementation for the language toggle feature flag. 
It is necessary to convert the value to a boolean otherwise the condition in the nunjucks templates will always evaluate to true, as environment variables are strings. So something like `toggle=false` is actually `toggle="false"` which is **truthy**. 
To enable toggling of the device intelligence function.
- [KIWI-2249](https://govukverify.atlassian.net/browse/KIWI-2249)
[KIWI-2249]: https://govukverify.atlassian.net/browse/KIWI-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2249 - Small fix for device intelligence feature flag

- package-lock.json
- package.json
What changed
Updated common express to use frontend-ui v2
Why did it change
Allows all the CRIs to import the GA4 on page load and use GA4
> feat: updating version to v12
