- package.json
Bump version number to see if that fixes yarn caching problems.
> chore: Bump package version

- package.json
Release v0.0.6 of common library code, including `authorization code` middleware
> chore: Bump package version v0.0.6

- src/routes/oauth2/middleware.js
- src/routes/oauth2/middleware.test.js
`AUTHORIZATION` endpoint is a `GET` method with query string params to match the Passport CRI implementation.
> fix: Use GET for authorization endpoint

- package.json
Update package.json for v0.0.7
> chore: Bump package version v0.0.7

- src/routes/oauth2/middleware.js
- src/routes/oauth2/middleware.test.js
`session-id` header was incorrect.
> fix: Use session-id as request header

- src/routes/oauth2/middleware.js
- src/routes/oauth2/middleware.test.js
Authorization Code is returned inside a value property
> fix: Use authorizationCode.value

- package.json
bump version in preparation for release 
> chore: Bump package version v0.0.9

- package.json
Update package.json to prepare a release
> chore: Update package.json for v0.0.11

- package.json
Bump version to 0.0.12 in preparation for a release.
> chore: Bump version to 0.0.12

- package.json
> chore: Bump version to 0.0.13

- package.json
- src/lib/axios.js
- src/lib/axios.test.js
- yarn.lock
> feat: Add pre-request logging for axios requests to help with debugging

- package.json
Bump version in preparation for release
> chore: Bump version to v0.0.15

- src/lib/oauth.js
- src/lib/oauth.test.js
- src/routes/oauth2/middleware.test.js
If `state` is available, use it in the redirect.
> fix: Use state if available on error and return redirects

- src/lib/helmet.js
Add helmet config based upon [di-authentication-frontend](https://github.com/alphagov/di-authentication-frontend/blob/main/src/config/helmet.ts) for reuse in common express apps.
- [KBV-562](https://govukverify.atlassian.net/browse/KBV-562)
> Add generic helmet config

- package.json
Update version in preparation of release.
> chore: Bump version to v0.0.20

- src/assets/javascript/cookies.js
> Remove {} from Programme Name

- package.json
Bump version in preparation for release.
> chore: Bump version to v0.0.21

- src/components/banner.njk
Update arial label to be consistent with screen
The visual label is not the same as the source code which can cause issues with a screen reader. Update the source code so it is consistent and will work with screen readers
- [KBV-574](https://govukverify.atlassian.net/browse/KBV-574)
- https://github.com/alphagov/di-authentication-frontend/pull/640
-
> fix: Update aria label to be consistent with screen

- package.json
- yarn.lock
Add missing dependancy.
i18next is needed for the script to run. It was omitted during the recent release.
> Bau release 0.0.25

- package.json
- yarn.lock
Add i18next dependancy as its currently a dev dependancy but for the dependancy to work with in a parent project.
> BAU-rel-0.0.26

- package.json
Move i18next into dependencies.
> BAU-rel-0.0.27

- .github/workflows/checks.yml
- package.json
Add matrix build to build using v16 and v18 
Remove restrictions in the engines section to allow usage in dependant packages.
> chore: Remove restrictions on node version to allow usage by 18.x

- src/components/banner.njk
- src/components/base-page.njk
Use cookie banner text from locales
> feat: Use cookie text from locales

- package.json
Update package version in preparation for release
> Release v0.0.29

- package.json
Updated release version from 0.0.29 -> 0.0.30
(To be merged after LIME-147 express PR is merged)
> LIME-147 - Release 0.0.30

- package.json
> Release v0.0.31

- package.json
Update version number for release.
> Release v0.0.32

- package.json
Updating version number for v0.0.33
> Release v0.0.33

- package.json
> Release v0.0.34

- package.json
Create Latest version for Ip address Change.
only  version number update.
- [OJ-923(https://govukverify.atlassian.net/browse/OJ-923)
> OJ-923 : Update Release Version for Client IP address in header

- src/lib/i18next/configure.js
- src/lib/i18next/configure.test.js
- src/lib/i18next/default-config.js
- src/lib/i18next/handler.js
- src/lib/i18next/handler.test.js
- src/lib/i18next/index.js
- src/lib/i18next/index.test.js
- cookieSecure & cookieDomain - used for sharing cookies between subdomains
- debug - used for local development
> feat: Allow customisable config via params

- package.json
Bumping version number for release
> chore: Bump version to v0.0.39

- package.json
Bumping version number for release
> chore: Bump version to v0.1.0

- package.json
- src/lib/i18next/handler.js
- src/lib/i18next/handler.test.js
- yarn.lock
- Node modules updated (or added) to the correct version to patch known vulnerabilities.
- [LIME-472](https://govukverify.atlassian.net/browse/LIME-472)
[LIME-472]: https://govukverify.atlassian.net/browse/LIME-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-472 - Node vulnerabilities fixed.

- package.json
> chore: Bump version v0.2.0

- package.json
- yarn.lock
> chore: Update i18next libraries

- package.json
Included a number dependabot updates, bumped as a major version to provide a more careful update
> Bump version v2.0.0

- package.json
> chore: Release v3.0.0

- src/components/base-form.njk
- src/components/base-page.njk
- src/lib/locals.js
- Add assetPath to templates
- assetPath is already defaulted to current behaviour of "/public"
- Add getAssetPath middleware to enable setting of assetPath by applications
- [OJ-1893](https://govukverify.atlassian.net/browse/OJ-1893)
[OJ-1893]: https://govukverify.atlassian.net/browse/OJ-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Use assetPath in templates

- package-lock.json
- package.json
> Bump version to 3.1.0

- src/lib/axios.js
Explicitly log required config parameters to avoid PII disclosure
> fix: Explicitly log required config properties to avoid PII disclosure

- package-lock.json
- package.json
> chore: Prepare for Release v3.2.0

- package-lock.json
- package.json
> chore: Prepare for Release v3.3.0

- package.json
Update package urls for provenance
> chore: Update package urls for provenance

- package-lock.json
- package.json
> chore: Prepare for release v3.4.0

- package-lock.json
- package.json
Pre-release version while #275 is being worked on and debugged
> chore: Prepare for pre-release 4.0.0

- package-lock.json
- package.json
Update to v5, skipping the v4 release branch as the preview release was manually tagged creating issues when publishing to npm.
> chore: Update to v5.0.0

- .eslintignore
- .eslintrc.js
- .github/workflows/checks.yml
- .github/workflows/pre-commit.yml
- .nycrc.yml
- .pre-commit-config.yaml
- .prettierignore
- CODEOWNERS
- package-lock.json
- package.json
- sonar-project.properties
- src/assets/javascript/.eslintrc.js
- src/assets/javascript/analytics/cookieBanner.js
- src/assets/javascript/analytics/cookies.js
- src/assets/javascript/analytics/core.js
- src/assets/javascript/analytics/ga4/init.js
- src/assets/javascript/analytics/ga4/pageViewTracker.js
- src/assets/javascript/analytics/loadAnalytics.js
- src/assets/javascript/analytics/ua/init.js
- src/assets/javascript/analytics/ua/legacy/cookies.js
- src/assets/javascript/application.js
- src/lib/axios.test.js
- src/routes/oauth2/middleware.test.js
Apply standardised repo config from other repos
- Update pre-commit hooks
- Remove a misconfigured Checkov hook
- Add an ESLint hook
- Address linting issues
- Use the prettier and jest plugins in ESLint
- Apply the recommended rules and styles for jest only for test files
- Install dev dependencies before running pre-commit to get ESLint plugins
- Allow unused variables if their names start with an underscore in test files
- Do linting as part of the pre-commit checks
- Update the linting commands
- Update the `.secrets.baseline` file to exclude specific keywords and files
- Update `package.json` to remove duplicated or unnecessary config
- Update linting and testing packages
- Set correct filters for source and test files for SonarCloud analysis
- Update code owners
> OJ-1495: Update repo config

- package-lock.json
- package.json
Major version bump to v6.0.0
To provide the GA4 implementation to CRI repositories
> Chore: Version update to v6.0.0

- package-lock.json
- package.json
> Chore: Version update to v6.1.0

- package-lock.json
- package.json
Releasing patch version of 5.x branch to include `tudorCrown`
> Chore: Version update to v5.1.0

- src/components/base-form.njk
- src/components/base-page.njk
Replace hardcoded texts by translation occurrences.
Extract hardcoded texts from one login language toggle component.
Replace hardcoded texts by translation occurrences.
- [DFC-467](https://govukverify.atlassian.net/browse/DFC-467)
[DFC-467]: https://govukverify.atlassian.net/browse/DFC-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-467: Use locale files for language toggle content

- package-lock.json
- package.json
Update to v6.2.0
To make the new optional language toggle available.
> Chore: Version update to v6.2.0

- package-lock.json
- package.json
New patch release to v6.2.1
New GTM domains were added to the CSP configuration in helmet.js
> Chore: Version update to v6.2.1

- README.md
- package-lock.json
- package.json
Analytics package peer dependency bumped to latest version
Upgrade is being rolled out across the CRIs, this change provides clean logs
> Chore: Upgrade analytics package peer dependency to v1.0.3

- package-lock.json
- package.json
> Chore: Release v6.2.2

- package-lock.json
- package.json
Minor version bump from 6.2.2 to 6.3.0
> Release/v6.2.2 -> v6.3.0

- .secrets.baseline
- package-lock.json
- package.json
- src/routes/oauth2/middleware.js
- src/routes/oauth2/middleware.test.js
Add personal data headers into session api call
- Add peerDependency for frontend-passthrough-headers
- Add new headers into axios post function for session api call
- 
- [DFC-575](https://govukverify.atlassian.net/browse/DFC-575)
[DFC-575]: https://govukverify.atlassian.net/browse/DFC-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-575: add personal data headers into session api call

- package-lock.json
- package.json
This release for v6.4.0 adds the txma-audit-encoded header passthrough.
- [DFC-575](https://govukverify.atlassian.net/browse/DFC-575)
[DFC-575]: https://govukverify.atlassian.net/browse/DFC-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DFC-575] chore: release v6.4.0

- README.md
- package-lock.json
- package.json
- src/components/base-form.njk
- src/components/base-page.njk
- src/lib/locals.js
- src/lib/settings.js
…ing by default
This allows users of common express to provide an `analyticsDataSensitive` value to control the analytics data sent by `v2.0.0` of the `@govuk-one-login/frontend-analytics` package.
The breaking change in `v2.0.0` of `@govuk-one-login/frontend-analytics` is that it defaults to a [new, more cautious approach, to reporting analytics](https://www.npmjs.com/package/@govuk-one-login/frontend-analytics#updating-to-v2). This will happen by default if teams update their version of `@govuk-one-login/frontend-analytics` to `v2.0.0`.
To retain the current `v1.x.x` approach to reporting analytics teams need to set the `isDataSensitive` flag to false, which can be done by providing a `analyticsDataSensitive` value to the `setGTM` function in this updated version of common-express. …
> [DAC-3526] - Common express updates to redact form answers from tracking by default

- package-lock.json
- package.json
Version bump from 6.4.1 to 6.5.0
Required to enable the CRIs to use the latest version of the analytics package
> Release/v6.4.1 -> v6.5.0

- package-lock.json
- package.json
Release v8.0.0 with new & renamed GA4 env variables.
> feat(release)!: v8.0.0

- README.md
- scripts/README.md
- src/README.md
- src/lib/README.md
- src/routes/README.md
Improve documentation:
- Update main README file
- Add more details explanation for the folders within `scripts`, `src`, `src/lib` and `src/routes`
> docs: Improve README documentation

- package-lock.json
- package.json
Create v8.0.2 that contains version bumps to fix high security vulnerabilities
> RELEASE: Create v8.0.2

- package-lock.json
- package.json
npm audit fix ran
Resolves;
https://github.com/govuk-one-login/ipv-cri-common-express/security/dependabot/28
https://github.com/govuk-one-login/ipv-cri-common-express/security/dependabot/29
- [OJ-2892](https://govukverify.atlassian.net/browse/OJ-2892)
[OJ-2892]: https://govukverify.atlassian.net/browse/OJ-2892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2892: 8.0.3 release - vulnerability fixes

- package-lock.json
- package.json
> BAU: Create version 8.1.0

- README.md
- src/lib/settings.js
Update README to reflect required env vars
We should always be providng values for these things to avoid the following syntax error 
- [OJ-2838](https://govukverify.atlassian.net/browse/OJ-2838)
[OJ-2838]: https://govukverify.atlassian.net/browse/OJ-2838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2838: Update README to reflect required env vars

- package-lock.json
- package.json
Created version 9.0.0
To release HMPO app changes that have major new functionality and a breaking change (minimum node version is now 20)
- [OJ-2938](https://govukverify.atlassian.net/browse/OJ-2938)
[OJ-2938]: https://govukverify.atlassian.net/browse/OJ-2938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2938: Create version 9.0.0

- package-lock.json
- package.json
Updated version number for release &
Removed extra class that was making the language toggle inconsistent between CRI and non CRI pages
Create consistency across the journeys
- [DFC-742](https://govukverify.atlassian.net/browse/DFC-742)
[DFC-742]: https://govukverify.atlassian.net/browse/DFC-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-742 Create Version 9.0.1

- package-lock.json
- package.json
Create version 10.0.0
To release new version with https://github.com/govuk-one-login/ipv-cri-common-express/pull/460#pullrequestreview-2546010472 that has a breaking change for some CRIs
- [OJ-2927](https://govukverify.atlassian.net/browse/OJ-2927)
[OJ-2927]: https://govukverify.atlassian.net/browse/OJ-2927?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2927: Create version 10.0.0

- package-lock.json
- package.json
Created version 10.0.1
Removed `role=complementary` from the govUkBanner label so that assistive tech does not deem it as important
- [OJ-2977](https://govukverify.atlassian.net/browse/OJ-2977)
[OJ-2977]: https://govukverify.atlassian.net/browse/OJ-2977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2977: Created version 10.0.1

- package-lock.json
- package.json
Create version 10.1.0
To release https://github.com/govuk-one-login/ipv-cri-common-express/pull/467
- [PYIC-7942](https://govukverify.atlassian.net/browse/PYIC-7942)
[PYIC-7942]: https://govukverify.atlassian.net/browse/PYIC-7942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PYIC-7942: Create version 10.1.0

- src/lib/error-handling.js
- src/routes/oauth2/middleware.js
Reverts most of https://github.com/govuk-one-login/ipv-cri-common-express/pull/467/files
I left a couple of them in and changed to info level as I think they are probably helpful for the future.
> PYIC-7942: Remove extra logging

- .github/workflows/check-pr.yml
- .github/workflows/publish.yml
- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
Update github-actions to the current latest version
The new version upgrades the deprecated SonarScan action.
Get the latest changes to the shared actions.
> BAU: Use the latest version of github-actions

- package-lock.json
- package.json
Create version 10.1.1
To release [477](https://github.com/govuk-one-login/ipv-cri-common-express/pull/477)
- [LIME-1543](https://govukverify.atlassian.net/browse/LIME-1543)
[LIME-1543]: https://govukverify.atlassian.net/browse/LIME-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Create version 10.3.0

- package-lock.json
- package.json
Create new release including package bumps to fix security vulnerabilities 
- xxios to 1.8.2 (manually regression tested the [absolute URLs breaking changes](https://github.com/axios/axios/releases/tag/v1.8.0) in orange CRIs and looks fine)
- @babel/runtime to 7.26.10
- [OJ-3093](https://govukverify.atlassian.net/browse/OJ-3093)
[OJ-3093]: https://govukverify.atlassian.net/browse/OJ-3093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release v10.5.0

- package-lock.json
- package.json
- src/bootstrap/index.js
- src/bootstrap/lib/overload-protection.js
- src/bootstrap/package-lock.json
- src/bootstrap/package.json
- test/bootstrap/lib/spec.overload-protection.js
- test/bootstrap/spec.index.js
Migrating overload-protection to common-express
> LIME-1545 - Moving overload protection to common-express

- package-lock.json
- package.json
Creating new release (v10.7.0) which includes support for device intelligence FEC package
> Release v10.7.0

- package-lock.json
- package.json
Creating new release (v10.7.1) which includes a fix for the device intelligence feature toggle
> Release v10.7.1

- package-lock.json
Ran `npm audit fix`
https://github.com/govuk-one-login/ipv-cri-common-express/security/dependabot/48
- [OJ-3216](https://govukverify.atlassian.net/browse/OJ-3216)
[OJ-3216]: https://govukverify.atlassian.net/browse/OJ-3216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3216: Fix low vulnerability

- package-lock.json
- package.json
Patch release for low vulnerability https://github.com/govuk-one-login/ipv-cri-common-express/security/dependabot/48
> Release version 11.0.1

- README.md
- Convert env vars to a table
- Add information so that we can easily map our env vars to the [frontend-analytics package docs](https://www.npmjs.com/package/@govuk-one-login/frontend-analytics)
To reduce confusion
> BAU: Update env vars table
